def set_options(opt):
  opt.tool_options("compiler_cxx")

def configure(conf):
  conf.check_tool("compiler_cxx")
  conf.check_tool("node_addon")
  conf.env.append_value('LINKFLAGS', '-L/usr/lib64/llvm -lclang -lLLVM-3.3'.split())

def build(bld):
  obj = bld.new_task_gen("cxx", "shlib", "node_addon") 
  obj.cxxflags = ["-g", "-std=c++0x", "-Wall"]
  obj.target = "ccomplete"
  obj.source = "src/ccomplete.cpp"